# Generated by Django 4.0.4 on 2022-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
