# Generated by Django 4.0.4 on 2022-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_navbar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_day',
            field=models.BooleanField(default=False),
        ),
    ]
