# Generated by Django 4.0.4 on 2022-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blog_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contact_time',
            field=models.TimeField(),
        ),
    ]
