# Generated by Django 4.0.4 on 2022-06-28 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_blog_contact_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contact_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
