# Generated by Django 4.0.4 on 2022-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_blog_date_blog_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pas',
            field=models.IntegerField(null=True),
        ),
    ]
