# Generated by Django 4.0.4 on 2022-07-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_blog_pas'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='image',
            field=models.ImageField(default=2, upload_to='navbar'),
            preserve_default=False,
        ),
    ]
