# Generated by Django 4.0.4 on 2022-07-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_navbar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='image',
            field=models.ImageField(upload_to='blogs'),
        ),
    ]
