# Generated by Django 4.0.4 on 2022-07-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_navbar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_type', to='blog.navbar'),
        ),
    ]
