# Generated by Django 4.0.6 on 2022-07-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_navbar_image_alter_navbar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogs'),
        ),
    ]
